production:
  adapter: mysql2
  encoding: utf8
  database: promobar_db
  username: root
  password: ''
  host: localhost
  socket: /var/lib/mysql/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  database: promobar_db
  username: root
  password: ''
  host: localhost
  socket: /var/lib/mysql/mysql.sock
test:
  adapter: mysql2
  encoding: utf8
  database: promobar_test_db
  username: root
  password: ''
  host: localhost
  socket: /var/lib/mysql/mysql.sock
